### ISSUE TITLE
Error adding entity None for domain device_tracker with platform sagemcom_fast

### ISSUE THREAD

**Issue by MagnusErler** [iMicknl/ha-sagemcom-fast#127]
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version            |   2024.5.0    |
| Integration version               |   0.3.2    |
| Sagemcom F@st model               |       |
| Sagemcom F@st firmware (optional) |       |

## Describe the bug

Found an error in Home Assistant Core log

## To Reproduce

Update Home Assistant to core 2024.5.0

## Expected behavior

No Error

## Log

```
Logger: homeassistant.components.device_tracker
Source: helpers/entity_platform.py:580
integration: Device tracker ([documentation](https://www.home-assistant.io/integrations/device_tracker), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+device_tracker%22))
First occurred: May 1, 2024 at 22:04:12 (1 occurrences)
Last logged: May 1, 2024 at 22:04:12

Error adding entity None for domain device_tracker with platform sagemcom_fast
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 716, in _async_add_entity
    entity_name = entity.name
                  ^^^^^^^^^^^
  File "/config/custom_components/sagemcom_fast/device_tracker.py", line 69, in name
    or self.device.mac_address
       ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Device' object has no attribute 'mac_address'. Did you mean: 'ip_address'?
```

[bug]

**Comment by iMicknl** [comment]
Thanks @MagnusErler! I need to see what changed in HA..

**Comment by MagnusErler** [comment]
Still present in v0.3.5

**Comment by iMicknl** [comment]
This looks like an underlying issue in the python-sagemcom-api library, where your device has not all properties available. Did you always encounter this issue, or only after updating?

**Comment by MagnusErler** [comment]
I have seen the warning in the HA log since HA 2024.5.0 (I have 2024.8.2 now) and ha-sagemcom-fast since v0.3.2

**Comment by jvberlo** [comment]
This error message still appears. in HA version  2024.10.1

2024-10-08 15:21:26.101 ERROR (MainThread) [homeassistant.components.device_tracker] Error adding entity None for domain device_tracker with platform sagemcom_fast
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 595, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 733, in _async_add_entity
    entity_name = entity.name
                  ^^^^^^^^^^^
  File "/config/custom_components/sagemcom_fast/device_tracker.py", line 70, in name
    or self.device.mac_address
       ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Device' object has no attribute 'mac_address'. Did you mean: 'ip_address'?

**Comment by MagnusErler** [comment]
Still present in v0.3.6 and HA 2024.11.2

**Comment by MagnusErler** [comment]
Still present in HA core version 2024.12.4

**Comment by MagnusErler** [comment]
Still present in HA 2025.1.3

**Comment by ddeconin-gh** [comment]
Its still present. Im on all latest.
