### ISSUE TITLE
No entity after upgrading to 2024.6

### ISSUE THREAD

**Issue by eyalco555** [iMicknl/ha-sagemcom-fast#136]
I have sagemcom 5657IL and all was fine till I upgraded to HA 2024.6.0 , then i got massage that it failed to set up.  TypeError async_get () takes 1 positional argument but 2 were given... 
Is there something to do to fix it ?

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version            |       |
| Integration version               |       |
| Sagemcom F@st model               |       |
| Sagemcom F@st firmware (optional) |       |

## Describe the bug

Give a clear and concise description of what the bug is.

## Expected behavior

Give a clear and concise description of what you expected to happen.

## Additional context

Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: June 8, 2024 at 9:41:11 PM (6 occurrences)
Last logged: June 8, 2024 at 11:22:33 PM

Error setting up entry 10.100.102.1 for sagemcom_fast
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sagemcom_fast/__init__.py", line 108, in async_setup_entry
    device_registry = hass.helpers.device_registry.async_get(hass)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: async_get() takes 1 positional argument but 2 were given
![Screenshot_20240609_002602_Home Assistant](https://github.com/iMicknl/ha-sagemcom-fast/assets/168588442/96be63ab-e98e-4ef0-9771-4b8d3848b888)

[bug]

**Comment by Floordb** [comment]
I got the same error. 

`Home Assistant Core
2024-06-10 08:07:49.420 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration sagemcom_fast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-10 08:08:25.653 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'sagemcom_fast' accesses hass.helpers.device_registry. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from device_registry directly at custom_components/sagemcom_fast/__init__.py, line 108: device_registry = hass.helpers.device_registry.async_get(hass), please create a bug report at https://github.com/imicknl/ha-sagemcom-fast/issues
2024-06-10 08:08:25.653 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.2.254 for sagemcom_fast
File "/config/custom_components/sagemcom_fast/__init__.py", line 108, in async_setup_entry
2024-06-10 08:20:01.103 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.2.254 for sagemcom_fast
File "/config/custom_components/sagemcom_fast/__init__.py", line 108, in async_setup_entry`

**Comment by iMicknl** [comment]
Is this fixed by the latest version? At the moment I am not at the location where I can test this integration, so it is hard to debug these weeks..

**Comment by eyalco555** [comment]
I don't know,  I had to go back to the previous version because I have to have devices tracking... 
Till I will find other solution or you  will fix it.. tnx for your help

**Comment by eyalco555** [comment]
> Is this fixed by the latest version? At the moment I am not at the location where I can test this integration, so it is hard to debug these weeks..

Doesn't work/fixed. 
Pls fix it,  it means a lot to me.

**Comment by iMicknl** [comment]
> > Is this fixed by the latest version? At the moment I am not at the location where I can test this integration, so it is hard to debug these weeks..
> 
> 
> 
> Doesn't work/fixed. 
> 
> Pls fix it,  it means a lot to me. 

What is the error message you receive?

**Comment by eyalco555** [comment]
> > > Is this fixed by the latest version? At the moment I am not at the location where I can test this integration, so it is hard to debug these weeks..
> > 
> > 
> > Doesn't work/fixed.
> > Pls fix it,  it means a lot to me.
> 
> What is the error message you receive?

tnx for your response, i got this error , and if i try to reload it failed 
![2024-06-23 033021](https://github.com/iMicknl/ha-sagemcom-fast/assets/168588442/a923c36b-f377-45c8-8aa1-b19dbb907315)

i cant trace all of my devices (device_tracker...not provided).
for exsample : 
Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 3:18:09 AM (2 occurrences)
Last logged: 3:21:20 AM

Error setting up entry 10.100.102.1 for sagemcom_fast
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sagemcom_fast/__init__.py", line 108, in async_setup_entry
    device_registry = hass.helpers.device_registry.async_get(hass)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: async_get() takes 1 positional argument but 2 were given

**Comment by eyalco555** [comment]
all fine now . i upgrade to v.3.3.3. 
I didn't see the upgrade on  HA  or HACS 
thanks for your halp !!!!
