### ISSUE TITLE
[F@st5370e] XMO_UNKNOWN_PATH_ERR on Device/DeviceInfo

### ISSUE THREAD

**Issue by Elox1991** [iMicknl/ha-sagemcom-fast#28]
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version            |    core-2021.11.1 / supervisor-2021.10.8  |
| Integration version               |   v.0.2.2    |
| Sagemcom F@st model               |   F@st5370e    |
| Sagemcom F@st firmware (optional) |       |

## Describe the bug
Installed using HACCS, added Sagemcom F@st at Integrations. Added my router ip and correct login information with authentication sha512.

"Failed to set up"
"Error setting up entry 192.168.1.1 for sagemcom_fast"

## Debug log
```
Logger: homeassistant.config_entries
Source: custom_components/sagemcom_fast/__init__.py:109
Integration: Sagemcom F@st (documentation)
First occurred: 19:31:45 (1 occurrences)
Last logged: 19:31:45

Error setting up entry 192.168.1.1 for sagemcom_fast
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/sagemcom_fast/__init__.py", line 109, in async_setup_entry
    gateway = await client.get_device_info()
  File "/usr/local/lib/python3.9/site-packages/sagemcom_api/client.py", line 326, in get_device_info
    data = await self.get_value_by_xpath("Device/DeviceInfo")
  File "/usr/local/lib/python3.9/site-packages/sagemcom_api/client.py", line 296, in get_value_by_xpath
    response = await self.__api_request_async([actions], False)
  File "/usr/local/lib/python3.9/site-packages/sagemcom_api/client.py", line 233, in __api_request_async
    raise UnknownPathException(action_error)
sagemcom_api.exceptions.UnknownPathException: {'code': 16777242, 'description': 'XMO_UNKNOWN_PATH_ERR'}
```

**Comment by iMicknl** [comment]
It seems that logging in works, however retrieving the DeviceInfo is perhaps not supported on your device. 

Do you have any Python knowledge?

**Comment by Elox1991** [comment]
Unfortunately not..

**Comment by Elox1991** [comment]
> It seems that logging in works, however retrieving the DeviceInfo is perhaps not supported on your device.
> 
> Do you have any Python knowledge?

Unfortunately not..

**Comment by Patrit73** [comment]
I have the same problem, Telia router, Sagemcom  f@st5370e…

**Comment by Fugitive470** [comment]
Hi Mick/iMicknl
Thanks for taking the time to work on this integration

If it helps, I have the exact same issue as Patrit73 above

(Swedish) Telia router, Sagemcom f@st5370e
Installation = Manual (Copy the custom_components/sagemcom_fast to your custom_components folder)
Python skills = zero :-(

LOG=
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/sagemcom_fast/__init__.py:109
Integration: Sagemcom F@st (documentation, issues)
First occurred: 20:41:55 (1 occurrences)
Last logged: 20:41:55

Error setting up entry 192.168.1.1 for sagemcom_fast
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/sagemcom_fast/__init__.py", line 109, in async_setup_entry
    gateway = await client.get_device_info()
  File "/usr/local/lib/python3.9/site-packages/sagemcom_api/client.py", line 326, in get_device_info
    data = await self.get_value_by_xpath("Device/DeviceInfo")
  File "/usr/local/lib/python3.9/site-packages/sagemcom_api/client.py", line 296, in get_value_by_xpath
    response = await self.__api_request_async([actions], False)
  File "/usr/local/lib/python3.9/site-packages/sagemcom_api/client.py", line 233, in __api_request_async
    raise UnknownPathException(action_error)
sagemcom_api.exceptions.UnknownPathException: {'code': 16777242, 'description': 'XMO_UNKNOWN_PATH_ERR'}

**Comment by iMicknl** [comment]
Could some of you try with 0.2.6? I wonder if this fixes your errors.

**Comment by Elox1991** [comment]
> Could some of you try with 0.2.6? I wonder if this fixes your errors.

Tried it, does not work.
```
Error setting up entry 192.168.1.1 for sagemcom_fast
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sagemcom_api/client.py", line 364, in get_device_info
    data = await self.get_value_by_xpath("Device/DeviceInfo")
  File "/usr/local/lib/python3.9/site-packages/sagemcom_api/client.py", line 311, in get_value_by_xpath
    response = await self.__api_request_async([actions], False)
  File "/usr/local/lib/python3.9/site-packages/sagemcom_api/client.py", line 235, in __api_request_async
    raise UnknownPathException(action_error)
sagemcom_api.exceptions.UnknownPathException: {'code': 16777242, 'description': 'XMO_UNKNOWN_PATH_ERR'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/sagemcom_fast/__init__.py", line 105, in async_setup_entry
    gateway = await client.get_device_info()
  File "/usr/local/lib/python3.9/site-packages/sagemcom_api/client.py", line 367, in get_device_info
    data = await self.get_values_by_xpaths(
  File "/usr/local/lib/python3.9/site-packages/sagemcom_api/client.py", line 333, in get_values_by_xpaths
    response = await self.__api_request_async(actions, False)
  File "/usr/local/lib/python3.9/site-packages/sagemcom_api/client.py", line 235, in __api_request_async
    raise UnknownPathException(action_error)
sagemcom_api.exceptions.UnknownPathException: {'code': 16777242, 'description': `'XMO_UNKNOWN_PATH_ERR'}
```

**Comment by molexx** [comment]
Same error here on a Fast 5364.

I've had a poke about in the browser devtools, sending any successful json-req request for a second time returns XMO_UNKNOWN_PATH_ERROR in the response, so perhaps this is due to the `cnonce`?

**Comment by lrljoe** [comment]
Experiencing the same, also on a Fast 5364

**Comment by molexx** [comment]
Confirmed this is still the same issue on 0.3.1.

**Comment by Darsma** [comment]
Confirmed this is still on 0.3.6

**Comment by Darsma** [comment]
HA versions:
Core 2025.1.4
Supervisor 2024.12.3
Operating System 14.1
Frontend 20250109.2

Integration version: 0.3.6

Error in the logs:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/sagemcom_api/client.py", line 507, in get_device_info
    data = await self.get_value_by_xpath("Device/DeviceInfo")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/sagemcom_api/client.py", line 421, in get_value_by_xpath
    response = await self.__api_request_async([actions], False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/sagemcom_api/client.py", line 309, in __api_request_async
    result = await self.__post(api_host, form_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/sagemcom_api/client.py", line 276, in __post
    raise UnknownPathException(action_error)
sagemcom_api.exceptions.UnknownPathException: {'code': 16777242, 'description': 'XMO_UNKNOWN_PATH_ERR'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sagemcom_fast/__init__.py", line 94, in async_setup_entry
    gateway = await client.get_device_info()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/sagemcom_api/client.py", line 510, in get_device_info
    data = await self.get_values_by_xpaths(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<8 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/sagemcom_api/client.py", line 454, in get_values_by_xpaths
    response = await self.__api_request_async(actions, False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/sagemcom_api/client.py", line 309, in __api_request_async
    result = await self.__post(api_host, form_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/sagemcom_api/client.py", line 276, in __post
    raise UnknownPathException(action_error)
sagemcom_api.exceptions.UnknownPathException: {'code': 16777242, 'description': 'XMO_UNKNOWN_PATH_ERR'}
```
