### ISSUE TITLE
Sagemcom F@st 3865b don't login

### ISSUE THREAD

**Issue by papapingouin-be** [iMicknl/ha-sagemcom-fast#31]
Hello i try  Sagemcom F@st 3865b | Proximus (b-box3) | md5,
and I have this message : Unexpected error

Debug info:
2022-01-04 11:19:26 ERROR (MainThread) [custom_components.sagemcom_fast.config_flow] <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
Traceback (most recent call last):
File "/config/custom_components/sagemcom_fast/config_flow.py", line 65, in async_step_user
return await self.async_validate_input(user_input)
File "/config/custom_components/sagemcom_fast/config_flow.py", line 50, in async_validate_input
await client.login()
File "/usr/local/lib/python3.9/site-packages/sagemcom_api/client.py", line 265, in login
response = await self.__api_request_async([actions], True)
File "/usr/local/lib/python3.9/site-packages/sagemcom_api/client.py", line 198, in __api_request_async
raise UnknownException(result)
sagemcom_api.exceptions.UnknownException: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

Thanks 
Laurent

**Comment by iMicknl** [comment]
I don't think that your device is supported unfortunately, if you see a 404 error. This means that the API we use is just not there.
