### ISSUE TITLE
Missing MAC address?

### ISSUE THREAD

**Issue by raolss** [iMicknl/ha-sagemcom-fast#38]
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version            |   2022.2.9    |
| Integration version               |   0.25    |
| Sagemcom F@st model               |       |
| Sagemcom F@st firmware (optional) |   FAST3890V3_WIFIHUBC2_sw18.76.10.10o-17    |

## Describe the bug

Integration not configured 

## Expected behavior

Give a clear and concise description of what you expected to happen.

## Screenshots

Logger: homeassistant.config_entries
Source: helpers/device_registry.py:132
First occurred: 20:12:55 (1 occurrences)
Last logged: 20:12:55

Error setting up entry 192.168.0.1 for sagemcom_fast
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/sagemcom_fast/__init__.py", line 125, in async_setup_entry
    device_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 336, in async_get_or_create
    connections = _normalize_connections(connections)
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 850, in _normalize_connections
    return {
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 851, in <setcomp>
    (key, format_mac(value)) if key == CONNECTION_NETWORK_MAC else (key, value)
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 132, in format_mac
    if len(to_test) == 17 and to_test.count(":") == 5:
TypeError: object of type 'NoneType' has no len()

## Additional context

[bug]

**Comment by M4D1NG3R** [comment]
This bug should be fixed with release 0.2.6
