### ISSUE TITLE
Unable to connect to KPN Sagemcom F5359

### ISSUE THREAD

**Issue by mathijs5** [iMicknl/ha-sagemcom-fast#4]
Hi!

I installed the component, however it does not seem to work with the KPN model Sagemcom F5359. I tried the following combinations;
- admin + password in MD5 and sha512
- guest + password in MD5 and sha512
- guest + no password in MD5 and sha512
- no credentials in MD5 and sha512
- All of the above using ip adress and the url "mijnmodem.kpn"

`Config entry 'UPnP/IGD' for upnp integration not ready yet. Retrying in 80 seconds`

Not 100% sure this traceback is related;
```
2021-02-05 20:03:44 ERROR (MainThread) [homeassistant.components.system_health] Error fetching system info for cloud - can_reach_cloud
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/system_health/__init__.py", line 212, in async_check_can_reach_url
await session.get(url, timeout=5)
File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
await resp.start(conn)
File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
self._continue = None
File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

**Comment by iMicknl** [comment]
`Config entry 'UPnP/IGD' for upnp integration not ready yet. Retrying in 80 seconds`

This one should not be related to this integration. The other error could be related, most of the Sagemcom devices just have a connection time-out when the hashing method is not the right one.

Could you try to log in via the router web interface, and run the following command via your developer console;

```javascript
$.xmo.getValuesTree("Device/DeviceInfo")
```

and 

```javascript
$.xmo.getValuesTree("*")
```

It would be better to track this in https://github.com/iMicknl/python-sagemcom-api, since this is probably not related to the Home Assistant integration.
