### ISSUE TITLE
Cannot initiluze after upgrade 

### ISSUE THREAD

**Issue by raolss** [iMicknl/ha-sagemcom-fast#57]
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version            |   Home Assistant 2023.5.2Supervisor 2023.04.1Operating System 10.1Frontend-version: 20230503.2 - latest   |
| Integration version               |   latest 0.2.6    |
| Sagemcom F@st model               |       |
| Sagemcom F@st firmware (optional) |       |
FAST3890V3_WIFIHUBC2

## Describe the bug

Doesn't initilize

## Expected behavior

Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by djfanatix** [comment]
Yep, having the same issue

**Comment by iMicknl** [comment]
Didn't know people still used this integration, will fix the breaking change in 2023.5 ;-).

**Comment by raolss** [comment]
Thanks! I use it for presence detection of family members. Have found any other reliable solution.

**Comment by kubalobo** [comment]
I'm also using this integration and can't wait for a fix! :)
Thank you!

**Comment by iMicknl** [comment]
Can you let me know if v0.2.7 fixes the issue? I am not able to test at the moment.

**Comment by raolss** [comment]
Problem seems to remain.

Logger: homeassistant.config_entries
Source: loader.py:1045
First occurred: 07:38:01 (2 occurrences)
Last logged: 07:49:48

Error setting up entry 192.168.0.1 for sagemcom_fast
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/sagemcom_fast/__init__.py", line 127, in async_setup_entry
    device_registry = await hass.helpers.device_registry.async_get_registry()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1045, in __getattr__
    value = getattr(self._module, attr)
AttributeError: module 'homeassistant.helpers.device_registry' has no attribute 'async_get_registry'
