### ISSUE TITLE
Login issue?

### ISSUE THREAD

**Issue by raolss** [iMicknl/ha-sagemcom-fast#61]
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version            |       | Home Assistant 2023.5.4
Supervisor 2023.04.1
Operating System 10.1
Frontend-version: 20230503.3 - latest
| Integration version               |       | 0.2.8
| Sagemcom F@st model               |       |
| Sagemcom F@st firmware (optional) |    FAST3890V3_WIFIHUBC2_sw18.76.15.17w-6   | FAST3890V3_WIFIHUBC2_sw18.76.15.17w-6

Logginformation (FEL)
Felet härrör från en anpassad integration.
Logger: custom_components.sagemcom_fast
Source: custom_components/sagemcom_fast/__init__.py:70
Integration: Sagemcom F@st ([documentation](https://github.com/imicknl/ha-sagemcom-fast), [issues](https://github.com/imicknl/ha-sagemcom-fast/issues))
First occurred: 22:24:23 (2 occurrences)
Last logged: 22:50:02

{'code': 16777224, 'description': 'XMO_LOGIN_RETRY_ERR'}
Traceback (most recent call last):
  File "/config/custom_components/sagemcom_fast/__init__.py", line 70, in async_setup_entry
    await client.login()
  File "/usr/local/lib/python3.10/site-packages/sagemcom_api/client.py", line 270, in login
    response = await self.__api_request_async([actions], True)
  File "/usr/local/lib/python3.10/site-packages/sagemcom_api/client.py", line 240, in __api_request_async
    raise UnknownException(action_error)
sagemcom_api.exceptions.UnknownException: {'code': 16777224, 'description': 'XMO_LOGIN_RETRY_ERR'}

**Comment by raolss** [comment]
Removed the integration and added it again with SHA512, now it's working again
