### ISSUE TITLE
Sagemcom Fast5688sAttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setups'

### ISSUE THREAD

**Issue by keesfluitman** [iMicknl/ha-sagemcom-fast#68]
I believe it used to work. Been back using Home Assistant and now I see this error.
```
Logger: homeassistant.config_entries
Source: custom_components/sagemcom_fast/__init__.py:140
Integration: Sagemcom F@st ([documentation](https://github.com/imicknl/ha-sagemcom-fast), [issues](https://github.com/imicknl/ha-sagemcom-fast/issues))
First occurred: September 15, 2023 at 1:00:09 AM (3 occurrences)
Last logged: 4:04:47 PM
Error setting up entry 192.168.1.1 for sagemcom_fast

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/sagemcom_fast/__init__.py", line 140, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setups'
```

**Comment by iMicknl** [comment]
@keesfluitman which version of Home Assistant do you run?

**Comment by keesfluitman** [comment]
> @keesfluitman which version of Home Assistant do you run?

thanks. i did indeed need to update badly. But now I just get failed to connect. So I guess things have changed. have to try to get logs to work and then I'll get back to you.

**Comment by iMicknl** [comment]
Fixed in latest version.
