### ISSUE TITLE
Proximus router doesn't show any entities.

### ISSUE THREAD

**Issue by ddeconin-gh** [iMicknl/ha-sagemcom-fast#80]
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version            | 2023.12.4    |
| Integration version               |    0.28   |
| Sagemcom F@st model               |   FAST3890V3_DELTA-SIP    |
| Sagemcom F@st firmware (optional) |  FAST3890V3_DELTA-SIP_sw05.76.9.7k-3     |

## Describe the bug

When connecting to a Proximus bbox, no entities are showing up.

Error log shows errors

## To Reproduce

connect to proximus router

## Expected behavior

Give a clear and concise description of what you expected to happen.

## Additional context

2024-01-03 12:39:43.550 ERROR (MainThread) [homeassistant.components.device_tracker] Error adding entities for domain device_tracker with platform sagemcom_fast
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 584, in _async_add_entity
    entity_name = entity.name
                  ^^^^^^^^^^^
  File "/config/custom_components/sagemcom_fast/device_tracker.py", line 99, in name
    or self.device.mac_address
       ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Device' object has no attribute 'mac_address'
2024-01-03 12:39:43.552 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up sagemcom_fast platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 369, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 584, in _async_add_entity
    entity_name = entity.name
                  ^^^^^^^^^^^
  File "/config/custom_components/sagemcom_fast/device_tracker.py", line 99, in name
    or self.device.mac_address
       ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Device' object has no attribute 'mac_address'
[bug]

**Comment by iMicknl** [comment]
Could you try the latest version and report again? I will be working on adding better diagnostics to the integration, so we can more easily tackle such issues.

**Comment by ddeconin-gh** [comment]
Works fine now, thx!
